<?php
/****
  Toujours ouvrir la balise de php sans la refermer
***/

/*****
* implement hook_menu()
* create menu item
new_page_menu function will create a menu item which can be access with localhost/path/to/new_page
*/

function new_page_menu() {
     $items = array();
     $items['new_page'] = array(
        'title'             =>  'Nouvelle Page',  //page title
        'description'       =>  'Page description information',  //description show when mouse hover on link
        //'type' => MENU_NORMAL_ITEM, // add in the custom menu like a link
        'page callback'     =>  'new_page_create',  //callback function which is invoked when menu item is called.
        'access callback'   =>  true,  //any user can access this page
       );
      return $items;
}

/*****
* implement hook_theme()
*/
function new_page_theme() {
        $themes = array();
        $themes['mynew_custompage'] = array(
        'variables' => array(),
        'template' => 'templates/mynew_custompage',
        'path' => drupal_get_path('module', 'new_page'),
      );
     return $themes;

}
/*****
* implement page callback()
*/
function new_page_create() {
	return theme('mynew_custompage');
}


/*****
     Create a custom block for my module qui affiche le nom l'utilisateur courant, son rôle, inscription date, last_logged_time,
***/
